networks:
  app_network:
    driver: bridge


services:
  backend:
    build: .
    image: ui_bot
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis
      - ollama
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ~/.models:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network


volumes:
  redis_data:
