services:

  backend:
    container_name: backend
    build:
       context: .
    image: ${DOCKER_USERNAME?Variable not set}/ui_bot:backend
    ports:
      - 8080:8000
    restart: always
    depends_on:
      - ollama
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY?Variable not set}


  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  promptfoo:
    container_name: promptfoo
    image: ghcr.io/promptfoo/promptfoo:latest
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY?Variable not set}
    volumes:
      - ./tests/promptfoo:/tests
      - /home/vmware/.promptfoo:/home/promptfoo/.promptfoo