name: CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REACT_APP_BACKEND_API_URL: ${{ secrets.REACT_APP_BACKEND_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker compose -f docker-compose.yml build

      - name: Run Docker Images
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Remove unused Docker Images
        run: |
          docker image prune -a -f

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker compose -f docker-compose.yml push
