name: Test Model by PromptFoo

on: workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Exec promptfoo conteiner bash
        run: |
          docker exec promptfoo sh -c "cd /tests && promptfoo eval"
