name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name: Check code with ruff
        run: ruff check --output-format=github .

      - name: Format code using ruff
        run: ruff format
