name: Ruff
on: [push]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check --fix --output-format=github .
          src: "./backend"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Changes by ruff code formater"
